package common;

public enum PageType {
	SITE_HOME_PAGE, SITE_REGISTRATION_PAGE, SITE_LOGIN_PAGE, SITE_PRODUCT_DETAIL_PAGE, USERS_MANAGEMENT_PAGE,
	SITE_CART_PAGE, SITE_CHECKOUT_PAGE, SITE_ACCOUNT_PAGE, PRODUCTS_MANAGEMENT_PAGE
}
